apiVersion: v1
kind: Service
metadata:
  name: calculation-service
spec:
  selector:
    app: frontend  # Assuming both containers share the same label
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001  # Port for the calculation-service container