apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculation-deployment
spec:
  replicas: 1  # Set the number of replicas based on the desired redundancy
  selector:
    matchLabels:
      app: calculation
  template:
    metadata:
      labels:
        app: calculation
    spec:
      nodeSelector:
        node.kubernetes.io/microk8s-worker: "microk8s-worker"
      containers:
        - name: calculation-service
          image: looknat/calculator-service:release-3
          ports:
            - containerPort: 5001