apiVersion: v1
kind: Service
metadata:
  name: classification-service
spec:
  selector:
    app: frontend  # Assuming both containers share the same label
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002  # Port for the calculation-service container