apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000  # Use port 5000 for the service
    targetPort: 5000  # Route traffic to pods on port 5000
  type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: calculation-service
# spec:
#   selector:
#     app: frontend  # Assuming both containers share the same label
#   ports:
#     - protocol: TCP
#       port: 5001
#       targetPort: 5001  # Port for the calculation-service container