apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2  # Set the number of replicas based on the desired redundancy
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - osboxes
      containers:
        - name: frontend
          image: looknat/frontend-service:release-10
          ports:
            - containerPort: 5000
        - name: calculation-service
          image: looknat/calculator-service:release-3
          ports:
            - containerPort: 5001
        - name: classification-service
          image: looknat/classification-service:release-2
          ports:
            - containerPort: 5002
        - name: risk-service
          image: looknat/risk-service:release-2
          ports:
            - containerPort: 5003
