FROM python:3.9.10-slim@sha256:9b07a53ef1744bd8c85562577f2bed889c90b372eb2cdd00849b7127bd68636c

WORKDIR /app

RUN apt-get update \
    && apt-get install -y iputils-ping curl nano \
    && rm -rf /var/lib/apt/lists/*


COPY classification.py .

RUN pip install Flask Flask-CORS

EXPOSE 5002

CMD ["python", "classification.py"]
