FROM python:3.9.10-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y iputils-ping curl nano \
    && rm -rf /var/lib/apt/lists/*

COPY risk.py .

RUN pip install Flask Flask-CORS requests

EXPOSE 5003

CMD ["python", "risk.py"]
