apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  externalIPs:
    - 192.168.0.107
  ports:
  - protocol: TCP
    port: 5000  # Use port 5000 for the service
    targetPort: 5000  # Route traffic to pods on port 5000
  type: LoadBalancer
