apiVersion: v1
kind: Service
metadata:
  name: risk-service
spec:
  selector:
    app: risk  # Assuming both containers share the same label
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003  # Port for the calculation-service container